apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorecards-app
  labels:
    app: scorecards-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scorecards-app
  template:
    metadata:
      labels:
        app: scorecards-app
    spec:
      containers:
      - name: scorecards-app
        image: benjamincrom/livebaseballscorecards:harness_build
        ports:
        - containerPort: 80

